# Generated by Django 5.2.6 on 2025-10-24 00:24

from django.db import migrations
from django.contrib.postgres.operations import CreateExtension


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_review'),
    ]

    operations = [
        # Для FTS (если нужно)
        CreateExtension('pg_trgm'),  # полезно для ilike/icontains
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS store_product_price_idx ON store_product (price);"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS store_product_stock_idx ON store_product (stock);"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS store_product_genre_idx ON store_product (genre_id);"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS store_review_product_rating_idx ON store_review (product_id, rating);"
        ),
        # Для ускорения поиска по названию/описанию (trigram)
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS store_product_name_trgm_idx ON store_product USING GIN (name gin_trgm_ops);"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS store_product_desc_trgm_idx ON store_product USING GIN (description gin_trgm_ops);"
        ),
        # Если хочешь FTS:
        # migrations.RunSQL(
        #   \"\"\"CREATE INDEX IF NOT EXISTS store_product_fts_idx
        #       ON store_product
        #       USING GIN (to_tsvector('russian', coalesce(name,'') || ' ' || coalesce(description,'')));
        #   \"\"\"
        # ),
    ]
