# Generated by Django 5.2.6 on 2025-10-24 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_paymentmethod_usersettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='method',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.PROTECT, to='store.paymentmethod'),
            preserve_default=False,
        ),
    ]
