# Generated by Django 5.2.6 on 2025-10-24 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='saved_filters',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='date_format',
            field=models.CharField(default='d.m.Y', max_length=20),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='number_format',
            field=models.CharField(default='1 234,56', max_length=20),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='page_size',
            field=models.PositiveIntegerField(default=12),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='theme',
            field=models.CharField(choices=[('light', 'Light'), ('dark', 'Dark')], default='light', max_length=10),
        ),
    ]
