# Generated by Django 5.2.6 on 2025-11-10 17:29

from django.db import migrations

POSTGRES_SQL = [
    """
    CREATE OR REPLACE VIEW store_v_product_catalog AS
    SELECT
        p.id                     AS product_id,
        p.name                   AS name,
        g.name                   AS genre,
        p.price                  AS price,
        p.stock                  AS stock,
        COALESCE(AVG(r.rating)::numeric(10,2), 0) AS avg_rating,
        COALESCE(
            string_agg(
                DISTINCT concat_ws('-', pr.min_players::text, pr.max_players::text),
                ';' ORDER BY concat_ws('-', pr.min_players::text, pr.max_players::text)
            ),
            ''
        ) AS player_ranges
    FROM store_product p
    LEFT JOIN store_genre g ON g.id = p.genre_id
    LEFT JOIN store_review r ON r.product_id = p.id
    LEFT JOIN store_product_player_ranges ppr ON ppr.product_id = p.id
    LEFT JOIN store_playerrange pr ON pr.id = ppr.playerrange_id
    GROUP BY p.id, p.name, g.name, p.price, p.stock;
    """,

    """
    CREATE OR REPLACE VIEW store_v_order_summary AS
    SELECT
        o.id                             AS order_id,
        o.order_date                     AS order_date,
        os.name                          AS order_status,
        u.username                       AS username,
        COALESCE(SUM(oi.quantity * oi.price), 0)::numeric(12,2) AS items_total,
        COALESCE(pay.amount, 0)::numeric(12,2)                 AS payment_amount,
        ps.name                          AS payment_status
    FROM store_order o
    LEFT JOIN store_orderstatus os ON os.id = o.status_id
    LEFT JOIN auth_user u          ON u.id = o.user_id
    LEFT JOIN store_orderitem oi   ON oi.order_id = o.id
    LEFT JOIN store_payment pay    ON pay.order_id = o.id
    LEFT JOIN store_paymentstatus ps ON ps.id = pay.status_id
    GROUP BY o.id, o.order_date, os.name, u.username, pay.amount, ps.name;
    """,

    """
    CREATE OR REPLACE VIEW store_v_sales_daily AS
    SELECT
        date_trunc('day', o.order_date) AS day,
        COUNT(DISTINCT o.id) AS orders_count,
        COALESCE(SUM(oi.quantity * oi.price), 0)::numeric(12,2) AS revenue
    FROM store_order o
    LEFT JOIN store_orderitem oi ON oi.order_id = o.id
    GROUP BY 1
    ORDER BY 1;

    """,

    """
    CREATE OR REPLACE VIEW store_v_low_stock AS
    SELECT
        p.id AS product_id,
        p.name,
        p.stock
    FROM store_product p
    WHERE p.stock < 5
    ORDER BY p.stock ASC, p.name ASC;
    """,
]

def create_views(apps, schema_editor):
    vendor = schema_editor.connection.vendor
    sql_list = POSTGRES_SQL if vendor == "postgresql" else SQLITE_SQL
    for sql in sql_list:
        schema_editor.execute(sql)

def drop_views(apps, schema_editor):
    to_drop = [
        "store_v_low_stock",
        "store_v_sales_daily",
        "store_v_order_summary",
        "store_v_product_catalog",
    ]
    for name in to_drop:
        if schema_editor.connection.vendor == "postgresql":
            schema_editor.execute(f'DROP VIEW IF EXISTS "{name}" CASCADE;')
        else:
            schema_editor.execute(f'DROP VIEW IF EXISTS {name};')

class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_usersettings_saved_filters_usersettings_updated_at_and_more'),
    ]

    operations = [
        migrations.RunPython(create_views, reverse_code=drop_views),
    ]
